import logging
import hashlib
import json
from typing import Dict
import redis
from app.core.config import settings

from .booppa_ai_service import BooppaAIService

logger = logging.getLogger(__name__)


class AIService:
    """AI service for generating audit narratives - Now with Booppa specialization and caching"""

    def __init__(self):
        self.deepseek_key = None  # Will be set from settings
        self.openai_key = None
        self.ollama_url = None
        self.booppa_ai = BooppaAIService()
        self.cache = redis.from_url(settings.REDIS_URL, decode_responses=True)

    def _get_cache_key(self, assessment_data: Dict) -> str:
        """Generate a stable cache key based on assessment data"""
        data_str = json.dumps(assessment_data, sort_keys=True)
        return f"narrative_cache:{hashlib.sha256(data_str.encode()).hexdigest()}"

    async def generate_audit_narrative(
        self, assessment_data: Dict, use_fallback: bool = False
    ) -> str:
        """Generate audit narrative using Booppa-specialized AI with Redis caching"""
        cache_key = self._get_cache_key(assessment_data)
        try:
            # Check cache first
            cached_narrative = self.cache.get(cache_key)
            if cached_narrative:
                logger.info("Serving audit narrative from cache")
                return cached_narrative

            # Use Booppa AI service for specialized compliance reporting
            report = await self.booppa_ai.generate_compliance_report(assessment_data)

            # Format the report as narrative
            narrative = self._format_report_as_narrative(report)

            # Cache the result for 24 hours
            self.cache.setex(cache_key, 86400, narrative)

            logger.info(
                f"Generated Booppa-specialized audit narrative: {len(narrative)} chars"
            )
            return narrative

        except Exception as e:
            logger.error(f"Booppa AI service failed, falling back: {e}")
            return await self._generate_fallback_narrative(assessment_data)

    def _format_report_as_narrative(self, report: Dict) -> str:
        """Format the structured report as a narrative"""
        narrative = f"""BOOPPA COMPLIANCE AUDIT REPORT
================================================================================

COMPANY: {report['company_info']['name']}
WEBSITE: {report['company_info']['website']}
REPORT ID: {report['report_metadata']['report_id']}
DATE: {report['report_metadata']['generated_date']}

EXECUTIVE SUMMARY
--------------------------------------------------------------------------------
{report['executive_summary']}

RISK ASSESSMENT
--------------------------------------------------------------------------------
Overall Risk Score: {report['risk_assessment']['score']}/100
Risk Level: {report['risk_assessment']['level']} ({report['risk_assessment']['description']})

DETAILED FINDINGS
--------------------------------------------------------------------------------
"""

        for i, finding in enumerate(report["detailed_findings"], 1):
            narrative += f"\n{i}. {finding['severity']} - {finding['type'].replace('_', ' ').title()}\n"
            narrative += f"   {finding['description']}\n"
            narrative += f"   Priority: {finding['priority']}\n"
            narrative += "-" * 80 + "\n"

        narrative += f"""
RECOMMENDATIONS
--------------------------------------------------------------------------------
"""

        for i, rec in enumerate(report["recommendations"], 1):
            narrative += f"\n{i}. {rec['violation_type'].replace('_', ' ').title()} ({rec['severity']})\n"
            for action in rec["actions"]:
                narrative += f"   • {action}\n"
            narrative += f"   Timeline: {rec['timeline']}\n"

        narrative += f"""
BLOCKCHAIN EVIDENCE INSTRUCTIONS
--------------------------------------------------------------------------------
{report['blockchain_evidence']['purpose']}

Steps for evidence creation:
"""

        for step in report["blockchain_evidence"]["steps"]:
            narrative += f"• {step}\n"

        narrative += f"""
NEXT STEPS
--------------------------------------------------------------------------------
"""

        for step in report["next_steps"]:
            narrative += f"• {step}\n"

        narrative += f"""
LEGAL REFERENCES
--------------------------------------------------------------------------------
"""

        for ref in report["legal_references"]:
            narrative += f"• {ref['title']}: {ref['url']}\n"

        narrative += f"""
{report['disclaimer']}
================================================================================
Report generated by: {report['report_metadata']['ai_model']}
"""

        return narrative

    async def _generate_fallback_narrative(self, data: Dict) -> str:
        """Generate fallback narrative when specialized AI fails"""
        framework = data.get("framework", "compliance")
        return f"""AUDIT NARRATIVE (Fallback Mode):

Compliance assessment completed for {data.get('company_name', 'the organization')}.

Based on automated scanning, several compliance issues were identified that require attention.
It is recommended to review data protection practices against {framework} requirements.

For detailed Singapore-specific compliance guidance:
1. Consult PDPC guidelines at https://www.pdpc.gov.sg
2. Review PDPA legislation requirements
3. Consider engaging a qualified compliance professional

Note: This is a generic assessment. For Booppa-specialized analysis with Singapore legal references,
ensure the Booppa AI service is properly configured."""

    async def generate_short_summary(self, assessment_data: Dict) -> str:
        """Generate short summary for dashboard display"""
        try:
            report = await self.booppa_ai.generate_compliance_report(assessment_data)

            summary = f"""📊 Quick Compliance Summary

Company: {report['company_info']['name']}
Risk Level: {report['risk_assessment']['level']} ({report['risk_assessment']['score']}/100)

Key Issues:
"""

            # Add top 3 issues
            for finding in report["detailed_findings"][:3]:
                summary += f"• {finding['severity']}: {finding['type'].replace('_', ' ').title()}\n"

            summary += f"\nImmediate Actions: Address {len([f for f in report['detailed_findings'] if f['severity'] in ['CRITICAL', 'HIGH']])} high-priority issues"

            return summary

        except Exception as e:
            return f"Compliance scan completed. Review full report for details. (Error: {str(e)[:50]}...)"
