"""CSP Registration Readiness Baseline — Day-1 deliverable for the CSP pack.

A CSP Compliance Pack purchase (SGD 3,999 one-time, or SGD 299/mo) previously
delivered a two-line activation email with nothing to open. The full AML/CFT
programme genuinely cannot be written at purchase time — it is generated by
`csp_doc_generator` only once the CSP submits a profile describing its actual
business — but that is an argument for deferring the *programme*, not for
delivering nothing at all.

This module renders what CAN be established on day one: the buyer's
ACRA-verified legal entity (resolved through `evidence_enricher.fetch_acra_status`,
the same registry path Vendor Proof and the bundles already use), what the
purchase has provisioned, and an explicit checklist of what still needs the
CSP's own input before the 8 AML/CFT documents can be generated.

It is deliberately NOT the AML/CFT programme and says so in print. Same honesty
register as the MAS TRM baseline it is modelled on
(`trm_baseline_generator.generate_trm_baseline_pdf`): a structured starting
point, never a statement of compliance.
"""
import logging
from datetime import datetime, timezone
from io import BytesIO
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from app.services.pdf_styles import get_unified_styles
from app.core.company import COMPANY_NAME
from app.services.pdf_logo import draw_logo_header

logger = logging.getLogger(__name__)

# Bump when the visible structure of the baseline PDF changes.
CSP_BASELINE_SCHEMA_VERSION = 1

_TABLE_STYLE = TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("FONTSIZE", (0, 0), (-1, 0), 8.5),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
])

_ACTIVE_COLOR = "#065f46"
_READY_COLOR = "#1d4ed8"
_PENDING_COLOR = "#b45309"
_UNVERIFIED_COLOR = "#dc2626"

# What the buyer must supply before the 8 AML/CFT documents can be generated.
# Mirrors the real gates in app/api/csp.py: ToS acceptance (403 until accepted)
# then POST /csp/profile, which queues generate_csp_documents.
_OUTSTANDING_STEPS = [
    ("Accept the Terms of Service",
     "All five clauses must be confirmed at booppa.io/csp/dashboard. CSP endpoints stay "
     "locked until this is done."),
    ("Create your CSP profile",
     "Registered legal name, UEN, registered address, and your Registered Qualified "
     "Individual (RQI) details."),
    ("Declare your service mix",
     "Company formation, nominee director, nominee shareholder, registered address, "
     "corporate secretarial, shelf company — this scopes the AML/CFT programme to what "
     "you actually offer."),
    ("Name your AML compliance officer",
     "Required by the CSP Act 2024; recorded on your profile and cited in the generated "
     "programme."),
    ("Onboard your first client",
     "CDD/EDD, sanctions screening, and UBO records begin once a client exists."),
]


def _xml_escape(s: str) -> str:
    return (str(s or "")).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _kv_rows(pairs: List[tuple], s) -> Table:
    """Two-column label/value table — the entity + purchase blocks both use it."""
    rows = [
        [Paragraph(f"<b>{_xml_escape(k)}</b>", s["cell_b"]), v if hasattr(v, "wrap")
         else Paragraph(_xml_escape(v), s["cell"])]
        for k, v in pairs
    ]
    t = Table(rows, colWidths=[2.0 * inch, 4.9 * inch])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def generate_csp_baseline_pdf(data: Dict[str, Any]) -> bytes:
    """Render the CSP Registration Readiness Baseline.

    Expected `data`:
      company_name:  str   ACRA-resolved legal name of the BUYER (never a domain)
      website:       str | None
      plan_label:    str   e.g. "CSP Compliance Pack — Full"
      billing_label: str   e.g. "One-time purchase"
      generated_at:  str   optional, formatted date
      acra:          dict  the fetch_acra_status() result, or {} / {"found": False}
      provisioning:  list of {capability, status, detail}
    """
    s = get_unified_styles()
    company = data.get("company_name") or "Your Organisation"
    plan_label = data.get("plan_label") or "CSP Compliance Pack"
    billing_label = data.get("billing_label") or ""
    acra: Dict[str, Any] = data.get("acra") or {}
    provisioning: List[Dict[str, Any]] = data.get("provisioning") or []
    gen_at = data.get("generated_at") or datetime.now(timezone.utc).strftime("%d %B %Y")

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=0.7 * inch, rightMargin=0.7 * inch,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        title=f"CSP Registration Readiness Baseline — {company}",
    )
    story: list = []

    story.append(Paragraph("CSP Registration Readiness Baseline", s["title"]))
    # The assessed entity is ALWAYS the customer — labelled explicitly so the
    # header can never be read as Booppa (same fix as the TRM baseline v3).
    story.append(Paragraph(f"<b>Assessed Entity:</b> {_xml_escape(company)}", s["sub"]))
    story.append(Paragraph(
        f"{_xml_escape(plan_label)}"
        + (f" &middot; {_xml_escape(billing_label)}" if billing_label else "")
        + f" &middot; Generated {_xml_escape(gen_at)}", s["small"]))
    story.append(Paragraph(
        f"Prepared by {_xml_escape(COMPANY_NAME)} on behalf of {_xml_escape(company)}",
        s["small"]))
    story.append(Spacer(1, 10))

    # ── Scope — say plainly what this is NOT ────────────────────────────────
    story.append(Paragraph("Scope of this document", s["h2"]))
    story.append(Paragraph(
        "This baseline confirms the legal entity behind your Corporate Service Provider "
        "(CSP) Compliance Pack against the ACRA register, and records what your purchase "
        "has initialised. It is <b>not</b> your AML/CFT programme, and it is <b>not</b> a "
        "statement of compliance with the Corporate Service Providers Act 2024. Your "
        "AML/CFT programme, CDD manual, STR policy, nominee director procedure, risk "
        "assessment methodology, client onboarding kit, compliance calendar, and record-"
        "keeping policy are generated from your CSP profile &mdash; they cannot be written "
        "before we know the business they must govern. The outstanding steps below are what "
        "unlock them.",
        s["body"]))
    story.append(Spacer(1, 6))

    # ── 1. Verified entity ──────────────────────────────────────────────────
    story.append(Paragraph("1. Verified Legal Entity", s["h2"]))
    found = bool(acra.get("found"))
    if found:
        live = bool(acra.get("live"))
        status_text = _xml_escape(acra.get("entity_status") or "UNKNOWN")
        status_cell = Paragraph(
            f'<font color="{_ACTIVE_COLOR if live else _UNVERIFIED_COLOR}">'
            f'<b>{status_text}</b></font>', s["cell"])
        pairs = [
            ("ACRA registered name", acra.get("registered_name") or company),
            ("UEN", acra.get("uen") or "—"),
            ("Entity type", acra.get("entity_type") or "—"),
            ("ACRA status", status_cell),
            ("Registration date", acra.get("registration_date") or "—"),
            ("Website", data.get("website") or "—"),
            ("Source", "ACRA entity register via data.gov.sg"),
            ("Retrieved", gen_at),
        ]
        story.append(_kv_rows(pairs, s))
        if not live:
            story.append(Spacer(1, 6))
            story.append(Paragraph(
                f'<font color="{_UNVERIFIED_COLOR}"><b>Warning:</b> '
                f'{_xml_escape(acra.get("warning") or "This entity is not shown as live on the ACRA register.")}'
                "</font>", s["body"]))
    else:
        story.append(Paragraph(
            f'<font color="{_UNVERIFIED_COLOR}"><b>Not confirmed against the ACRA register.</b></font> '
            f"We could not match {_xml_escape(company)} to a live ACRA entity at the time of "
            "generation. This does not affect your access &mdash; but the legal name and UEN you "
            "enter on your CSP profile are what the generated AML/CFT documents will carry, so "
            "please confirm they match your ACRA registration exactly.",
            s["body"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Under the CSP Act 2024 a corporate service provider must itself be registered with "
        "ACRA. The entity confirmed above is the entity your compliance records, nominee "
        "director assessments, and STR decisions will be filed under.",
        s["small"]))
    story.append(Spacer(1, 14))

    # ── 2. What is initialised ──────────────────────────────────────────────
    if provisioning:
        story.append(Paragraph("2. What Your Purchase Has Initialised", s["h2"]))
        story.append(Paragraph(
            "&ldquo;Active&rdquo; capabilities are live in your workspace now. "
            "&ldquo;Ready&rdquo; capabilities are provisioned and waiting on the one-time "
            "setup step named in the detail column.",
            s["body"]))
        story.append(Spacer(1, 6))
        rows = [[
            Paragraph("<b>Capability</b>", s["cell_b"]),
            Paragraph("<b>Status</b>", s["cell_b"]),
            Paragraph("<b>Detail / Next Step</b>", s["cell_b"]),
        ]]
        for p in provisioning:
            st = (p.get("status") or "Ready")
            pcolor = _ACTIVE_COLOR if st.lower() == "active" else _READY_COLOR
            rows.append([
                Paragraph(_xml_escape(p.get("capability") or "—"), s["cell"]),
                Paragraph(f'<font color="{pcolor}"><b>{_xml_escape(st)}</b></font>', s["cell"]),
                Paragraph(_xml_escape(p.get("detail") or "—"), s["cell"]),
            ])
        t = Table(rows, colWidths=[2.2 * inch, 0.9 * inch, 3.8 * inch], repeatRows=1)
        t.setStyle(_TABLE_STYLE)
        story.append(t)
        story.append(Spacer(1, 14))

    # ── 3. What still needs your input ──────────────────────────────────────
    story.append(Paragraph("3. What Still Needs Your Input", s["h2"]))
    story.append(Paragraph(
        "Each step below is a gate, not a suggestion. The eight AML/CFT documents are "
        "generated only after your CSP profile exists, and they are issued as "
        "<b>drafts requiring your attestation</b> &mdash; you must review and approve each one "
        "before it carries any evidentiary weight.",
        s["body"]))
    story.append(Spacer(1, 6))
    rows = [[
        Paragraph("<b>#</b>", s["cell_b"]),
        Paragraph("<b>Step</b>", s["cell_b"]),
        Paragraph("<b>What we need from you</b>", s["cell_b"]),
        Paragraph("<b>Status</b>", s["cell_b"]),
    ]]
    for i, (step, detail) in enumerate(_OUTSTANDING_STEPS, start=1):
        rows.append([
            Paragraph(str(i), s["cell"]),
            Paragraph(_xml_escape(step), s["cell"]),
            Paragraph(_xml_escape(detail), s["cell"]),
            Paragraph(f'<font color="{_PENDING_COLOR}"><b>Outstanding</b></font>', s["cell"]),
        ])
    t = Table(rows, colWidths=[0.35 * inch, 1.75 * inch, 3.65 * inch, 1.15 * inch], repeatRows=1)
    t.setStyle(_TABLE_STYLE)
    story.append(t)
    story.append(Spacer(1, 14))

    # ── 4. Where the work is genuinely yours ────────────────────────────────
    story.append(Paragraph("4. Assessments You Must Perform Yourself", s["h2"]))
    story.append(Paragraph(
        "Two obligations under the CSP Act 2024 cannot be satisfied by a generated document, "
        "and this platform does not attempt to generate them:",
        s["body"]))
    story.append(Spacer(1, 4))
    for point in (
        "<b>Fit-and-proper assessment of nominee directors.</b> The assessment must be "
        "performed by the registered CSP. Booppa records your criminal, bankruptcy, and "
        "director-history checks, your outcome, and your written reasoning, then anchors the "
        "record on-chain with a one-year review date &mdash; it does not write the assessment "
        "for you.",
        "<b>STR filing decisions.</b> Every decision must be logged, including a decision "
        "<i>not</i> to file, with your rationale. That rationale is what answers an ACRA "
        "inspector asking why no report was made. Booppa stores and notarizes it; the "
        "reasoning is yours. Client notification is permanently disabled &mdash; tipping-off "
        "is an offence under CDSA s.48A.",
    ):
        story.append(Paragraph(f"&bull; {point}", s["body"]))
        story.append(Spacer(1, 4))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Recommended First Steps", s["h2"]))
    for step in (
        "Accept the Terms of Service and create your CSP profile &mdash; this queues generation "
        "of all eight AML/CFT documents.",
        "Confirm the legal name and UEN above match your ACRA registration exactly before "
        "submitting the profile.",
        "Review and attest each generated document; drafts are not evidence until approved.",
        "Import or onboard your client book so CDD, sanctions screening, and UBO records begin "
        "accruing an audit trail.",
    ):
        story.append(Paragraph(f"&bull; {step}", s["body"]))
        story.append(Spacer(1, 3))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        f"This document is generated by {COMPANY_NAME} for informational purposes only. It "
        "does not constitute legal or regulatory advice, is not an AML/CFT programme, and is "
        "not a statement of compliance with the Corporate Service Providers Act 2024. "
        f"Baseline schema v{CSP_BASELINE_SCHEMA_VERSION}.",
        s["small"]))

    doc._branding = data.get("white_label")
    doc.build(story, onFirstPage=draw_logo_header, onLaterPages=draw_logo_header)
    return buf.getvalue()
