"""Authenticated CRUD for the CMS, ported from `cms_admin/cms/admin_api.py`.

Mounted at `/admin/cms`, so these land at `/api/admin/cms/blogs/` — the exact
path the Next.js proxy already builds (it joins the segments and appends a
slash). Routes are therefore declared **with** trailing slashes, same reason as
`cms_public.py`: a 307 redirect can lose the body on POST/PUT.

The auth change is the point of this module. Django gated on a shared secret in
`X-Admin-Token` (`CMS_ADMIN_TOKEN`), checked frontend-side by a `_guard.ts` whose
entire test was `token.length > 10`. Here the router depends on `_admin_auth`,
the same gate as every other admin endpoint, so the admin bearer JWT the UI
already holds is sufficient and the second shared secret can be retired.

Divergences from the Django original, all deliberate — each was a defect there:

- List responses no longer carry `booking_token` or `tracking_token`. Those are
  the customer's own bearer-style secrets for the public booking/ticket-tracking
  pages; a list endpoint dumped every one of them. Detail responses still omit
  them too — nothing in the admin UI reads either field.
- Save failures return a generic 400 instead of `str(exc)`, which leaked raw
  psycopg2/IntegrityError text (table and column names) to the client.
- Booking `status` and ticket `status`/`priority` are constrained to known
  values; Django wrote any string straight through.
- PATCH writes only the fields actually supplied. Django's `update_fields` list
  was static, so a PATCH of `status` alone also rewrote `priority` and
  `assigned_to` from the in-memory row.
- `[:500]` hard caps are replaced with real `limit`/`offset`. The `{"results":
  [...]}` envelope is unchanged because `CmsCrud.tsx` reads a flat array.
"""

import logging
import re
import uuid
from datetime import datetime, timezone
from typing import Optional

from fastapi import (
    APIRouter,
    Body,
    Depends,
    File as FastAPIFile,
    Form,
    HTTPException,
    Query,
    Response,
    UploadFile,
)
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import selectinload

from app.api.admin import _admin_auth
from app.api.cms_public import _dj_dt, _image_url
from app.core.db import SessionLocal
from app.core.models import (
    BlogImage,
    BlogPost,
    CompliancePost,
    DemoBooking,
    RfpTip,
    SupportTicket,
    SupportTicketReply,
    VendorGuide,
)
from app.core.route_classes import RetryAPIRoute

logger = logging.getLogger(__name__)

router = APIRouter(route_class=RetryAPIRoute, dependencies=[Depends(_admin_auth)])

# The content routes are catch-alls: `/{kind}/` matches `/bookings/` just as
# happily as `/blogs/`, and FastAPI resolves in registration order. Keeping them
# on a second router that is included at the *bottom* of this file guarantees
# every literal path is tried first, whatever order the functions are written in.
content_router = APIRouter(route_class=RetryAPIRoute)


# ── Content types ─────────────────────────────────────────────────────────────

# kind -> (model, has_images). `blogs` is the only type with images or a category.
CONTENT_MODELS = {
    "blogs": (BlogPost, True),
    "rfp-tips": (RfpTip, False),
    "compliance": (CompliancePost, False),
    "vendor-guides": (VendorGuide, False),
}

WRITABLE_FIELDS = (
    "title",
    "slug",
    "content",
    "author",
    "cta1_text",
    "cta1_url",
    "cta2_text",
    "cta2_url",
    "published",
)

BOOKING_STATUSES = {"pending", "confirmed", "completed", "cancelled", "no_show"}
TICKET_STATUSES = {"open", "in_progress", "waiting", "resolved", "closed"}
TICKET_PRIORITIES = {"low", "medium", "high", "urgent"}

_SLUG_STRIP = re.compile(r"[^\w\s-]")
_SLUG_SPACE = re.compile(r"[-\s]+")


def _slugify(value: str) -> str:
    """Django's `django.utils.text.slugify`, minus the Unicode-normalisation
    branch we never used (titles are ASCII). Kept because slugs already in the
    table were generated by it and must stay stable."""
    value = _SLUG_STRIP.sub("", value).strip().lower()
    return _SLUG_SPACE.sub("-", value)


def _get_model(kind: str):
    entry = CONTENT_MODELS.get(kind)
    if not entry:
        raise HTTPException(status_code=404, detail="Unknown content type")
    return entry


def _is_aware_model(model) -> bool:
    """`blog_posts` timestamps are naive; the other three are `timestamptz`.
    See the CMS section note in `app/core/models.py` — the split is real in the
    database, so a value written into the wrong one raises on comparison."""
    return model is not BlogPost


def _now_for(model) -> datetime:
    return datetime.now(timezone.utc) if _is_aware_model(model) else datetime.utcnow()


def _serialize_post(post, *, include_images: bool = False) -> dict:
    data = {
        "id": str(post.id),
        "title": post.title,
        "slug": post.slug,
        "content": post.content,
        "author": post.author,
        "cta1_text": post.cta1_text,
        "cta1_url": post.cta1_url,
        "cta2_text": post.cta2_text,
        "cta2_url": post.cta2_url,
        "published": post.published,
        "published_at": _dj_dt(post.published_at),
        "created_at": _dj_dt(post.created_at),
        "updated_at": _dj_dt(post.updated_at),
    }
    if include_images:
        # Objects here, bare URL strings on the public endpoint. `CmsCrud.tsx`
        # reads `img.url` and `img.id` (to delete); `app/blog/page.tsx` does
        # `<Image src={p.images[0]}>`. Both shapes are load-bearing.
        data["images"] = [
            {"id": img.id, "url": _image_url(img.image), "caption": img.caption}
            for img in post.images
        ]
    return data


def _apply_writable(post, payload: dict, model) -> None:
    """Copy supplied writable fields onto the row and reproduce the publish
    side-effect the Django model's `save()` carried (`cms/models.py:30-47`):
    publishing stamps `published_at`, unpublishing clears it. Losing this would
    silently break ordering — the public endpoints sort by `published_at desc`
    and a null sorts to the end."""
    was_published = bool(post.published)
    for field in WRITABLE_FIELDS:
        if field in payload:
            setattr(post, field, payload[field])

    if post.published and not was_published and not post.published_at:
        post.published_at = _now_for(model)
    elif not post.published:
        post.published_at = None

    if not post.slug and post.title:
        post.slug = _slugify(post.title)[:240]

    post.updated_at = _now_for(model)


def _require_dict(payload) -> dict:
    if payload is None:
        return {}
    if not isinstance(payload, dict):
        raise HTTPException(status_code=400, detail="Invalid JSON body")
    return payload


def _commit(db, *, what: str):
    """Commit, or turn a driver error into a generic 400.

    Django returned `str(exc)` here, which handed the client raw database error
    text — constraint names, column names, sometimes the conflicting value. The
    common real case is a duplicate slug, so that one gets a useful message and
    everything else stays opaque."""
    try:
        db.commit()
    except SQLAlchemyError as exc:
        db.rollback()
        detail = "Could not save. A record with this slug may already exist."
        logger.warning("CMS admin %s failed: %s", what, exc)
        raise HTTPException(status_code=400, detail=detail)


# ── Content CRUD ──────────────────────────────────────────────────────────────


@content_router.get("/{kind}/")
def list_content(
    kind: str,
    limit: int = Query(default=200, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
):
    model, has_images = _get_model(kind)
    db = SessionLocal()
    try:
        query = db.query(model).order_by(model.created_at.desc())
        if has_images:
            query = query.options(selectinload(model.images))
        rows = query.limit(limit).offset(offset).all()
        return {
            "results": [_serialize_post(r, include_images=has_images) for r in rows]
        }
    finally:
        db.close()


@content_router.post("/{kind}/", status_code=201)
def create_content(kind: str, payload: dict = Body(default=None)):
    model, has_images = _get_model(kind)
    payload = _require_dict(payload)
    db = SessionLocal()
    try:
        post = model()
        post.published = False  # so `_apply_writable` sees a truthful prior state
        _apply_writable(post, payload, model)
        if not post.title:
            raise HTTPException(status_code=400, detail="title is required")
        if not post.slug:
            raise HTTPException(status_code=400, detail="slug is required")
        if post.content is None:
            post.content = ""
        db.add(post)
        _commit(db, what=f"create {kind}")
        db.refresh(post)
        data = _serialize_post(post, include_images=False)
        if has_images:
            data["images"] = []
        return data
    finally:
        db.close()


def _load(db, model, has_images: bool, item_id: str):
    query = db.query(model)
    if has_images:
        query = query.options(selectinload(model.images))
    try:
        row = query.filter(model.id == item_id).first()
    except SQLAlchemyError:
        # A non-UUID path segment is a 404, not a 500.
        db.rollback()
        row = None
    if row is None:
        raise HTTPException(status_code=404, detail="Not found")
    return row


@content_router.get("/{kind}/{item_id}/")
def get_content(kind: str, item_id: str):
    model, has_images = _get_model(kind)
    db = SessionLocal()
    try:
        post = _load(db, model, has_images, item_id)
        return _serialize_post(post, include_images=has_images)
    finally:
        db.close()


@content_router.put("/{kind}/{item_id}/")
@content_router.patch("/{kind}/{item_id}/")
def update_content(kind: str, item_id: str, payload: dict = Body(default=None)):
    model, has_images = _get_model(kind)
    payload = _require_dict(payload)
    db = SessionLocal()
    try:
        post = _load(db, model, has_images, item_id)
        _apply_writable(post, payload, model)
        _commit(db, what=f"update {kind}")
        db.refresh(post)
        return _serialize_post(post, include_images=has_images)
    finally:
        db.close()


@content_router.delete("/{kind}/{item_id}/", status_code=204)
def delete_content(kind: str, item_id: str):
    model, has_images = _get_model(kind)
    db = SessionLocal()
    try:
        post = _load(db, model, has_images, item_id)
        db.delete(post)
        _commit(db, what=f"delete {kind}")
        return Response(status_code=204)
    finally:
        db.close()


# ── Blog images ───────────────────────────────────────────────────────────────


@router.post("/blogs/{item_id}/images/", status_code=201)
async def upload_blog_image(
    item_id: str,
    image: UploadFile = FastAPIFile(...),
    caption: Optional[str] = Form(default=None),
):
    """Store a blog image on S3 and record its key.

    The Django version wrote to `/app/media` on an EFS mount and stored a
    MEDIA_ROOT-relative path. New uploads store an S3 key under `cms/`, which
    `_image_url` recognises and routes through `/api/public/cms-media/…`.
    Django-era rows keep working untouched — see `_image_url`.
    """
    from app.adapters.s3_storage import S3StorageAdapter

    adapter = S3StorageAdapter()
    content_type = (image.content_type or "").split(";")[0].strip().lower()
    if content_type not in adapter.ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported image type; allowed: "
                + ", ".join(sorted(adapter.ALLOWED_IMAGE_TYPES))
            ),
        )
    body = await image.read()

    db = SessionLocal()
    try:
        post = _load(db, BlogPost, True, item_id)
        ext = adapter.ALLOWED_IMAGE_TYPES[content_type]
        key = f"cms/blog_images/{post.id}/{uuid.uuid4().hex}{ext}"
        try:
            adapter.upload_image(body, key, content_type)
        except ValueError as exc:
            # Size/type rejection from the adapter — a client error, not a 500.
            raise HTTPException(status_code=400, detail=str(exc))
        except Exception:
            logger.exception("CMS image upload to S3 failed for blog %s", item_id)
            raise HTTPException(status_code=502, detail="Image storage unavailable")

        row = BlogImage(blog_post_id=post.id, image=key, caption=caption or None)
        db.add(row)
        _commit(db, what="create blog image")
        db.refresh(row)
        return {"id": row.id, "url": _image_url(row.image), "caption": row.caption}
    finally:
        db.close()


@router.post("/blogs/{item_id}/images/presign/")
def presign_blog_image(item_id: str, payload: dict = Body(...)):
    """Mint a direct-to-S3 upload ticket for a blog image.

    Step 1 of 2. The browser POSTs the file straight to S3 with the returned
    fields, then calls `…/images/confirm/` to record it. See
    `S3StorageAdapter.presign_image_upload` for why the multipart route through
    this service cannot carry a real image.
    """
    from app.adapters.s3_storage import S3StorageAdapter

    adapter = S3StorageAdapter()
    content_type = str(payload.get("content_type") or "").split(";")[0].strip().lower()
    if content_type not in adapter.ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported image type; allowed: "
                + ", ".join(sorted(adapter.ALLOWED_IMAGE_TYPES))
            ),
        )

    # Reject oversized files before the round-trip to S3. The presign policy
    # enforces this too — this is only a faster, clearer error for the admin.
    size = payload.get("size")
    if isinstance(size, int) and size > adapter.MAX_IMAGE_BYTES:
        raise HTTPException(
            status_code=400,
            detail=f"Image is {size} bytes; limit is {adapter.MAX_IMAGE_BYTES}",
        )

    db = SessionLocal()
    try:
        post = _load(db, BlogPost, False, item_id)
        ext = adapter.ALLOWED_IMAGE_TYPES[content_type]
        key = f"cms/blog_images/{post.id}/{uuid.uuid4().hex}{ext}"
    finally:
        db.close()

    try:
        presigned = adapter.presign_image_upload(key, content_type)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception:
        logger.exception("Presigned upload mint failed for blog %s", item_id)
        raise HTTPException(status_code=502, detail="Image storage unavailable")

    return {"key": key, "url": presigned["url"], "fields": presigned["fields"]}


@router.post("/blogs/{item_id}/images/confirm/", status_code=201)
def confirm_blog_image(item_id: str, payload: dict = Body(...)):
    """Record a browser-uploaded blog image. Step 2 of 2.

    The key is re-derived against this post rather than trusted: a caller could
    otherwise hand back any key in the bucket — which also holds customer PDPA
    reports and evidence packs — and have it served publicly through
    `/api/public/cms-media/…`. We also confirm the object really exists, so a
    failed browser upload cannot leave a row pointing at nothing.
    """
    from app.adapters.s3_storage import S3StorageAdapter

    adapter = S3StorageAdapter()
    key = str(payload.get("key") or "")

    db = SessionLocal()
    try:
        post = _load(db, BlogPost, False, item_id)

        expected_prefix = f"cms/blog_images/{post.id}/"
        if not key.startswith(expected_prefix) or "/" in key[len(expected_prefix):]:
            raise HTTPException(status_code=400, detail="Invalid image key")

        head = adapter.head_object(key)
        if head is None:
            raise HTTPException(
                status_code=400, detail="Upload not found; please retry"
            )
        if head.get("ContentLength", 0) > adapter.MAX_IMAGE_BYTES:
            raise HTTPException(status_code=400, detail="Image exceeds size limit")

        caption = payload.get("caption")
        row = BlogImage(blog_post_id=post.id, image=key, caption=caption or None)
        db.add(row)
        _commit(db, what="create blog image")
        db.refresh(row)
        return {"id": row.id, "url": _image_url(row.image), "caption": row.caption}
    finally:
        db.close()


@router.delete("/blogs/{item_id}/images/{image_id}/", status_code=204)
def delete_blog_image(item_id: str, image_id: int):
    db = SessionLocal()
    try:
        post = _load(db, BlogPost, False, item_id)
        row = (
            db.query(BlogImage)
            .filter(BlogImage.id == image_id, BlogImage.blog_post_id == post.id)
            .first()
        )
        if row is None:
            raise HTTPException(status_code=404, detail="Not found")
        # The S3 object is deliberately left in place: keys are immutable and
        # uuid-suffixed, so an orphan costs fractions of a cent and a delete
        # that raced a cached page would 404 a live image. Sweep separately.
        db.delete(row)
        _commit(db, what="delete blog image")
        return Response(status_code=204)
    finally:
        db.close()


# ── Demo bookings ─────────────────────────────────────────────────────────────


def _serialize_booking(b, *, include_token: bool = False) -> dict:
    data = {
        "id": str(b.id),
        "slot_id": b.slot_id,
        "slot_date": b.slot_date.isoformat() if b.slot_date else None,
        "start_time": b.start_time,
        "end_time": b.end_time,
        "customer_name": b.customer_name,
        "customer_email": b.customer_email,
        "customer_phone": b.customer_phone,
        "notes": b.notes,
        "status": b.status,
        "source": b.source,
        "created_at": _dj_dt(b.created_at),
        "updated_at": _dj_dt(b.updated_at),
    }
    if include_token:
        data["booking_token"] = b.booking_token
    return data


@router.get("/bookings/")
def list_bookings(
    limit: int = Query(default=200, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
):
    db = SessionLocal()
    try:
        rows = (
            db.query(DemoBooking)
            .order_by(DemoBooking.created_at.desc())
            .limit(limit)
            .offset(offset)
            .all()
        )
        # No `booking_token` here: it is the customer's own reschedule/cancel
        # credential, and Django emitted one per row on every list load.
        return {"results": [_serialize_booking(b) for b in rows]}
    finally:
        db.close()


def _load_booking(db, booking_id: str) -> DemoBooking:
    try:
        row = db.query(DemoBooking).filter(DemoBooking.id == booking_id).first()
    except SQLAlchemyError:
        db.rollback()
        row = None
    if row is None:
        raise HTTPException(status_code=404, detail="Not found")
    return row


@router.get("/bookings/{booking_id}/")
def get_booking(booking_id: str):
    db = SessionLocal()
    try:
        return _serialize_booking(_load_booking(db, booking_id))
    finally:
        db.close()


@router.put("/bookings/{booking_id}/")
@router.patch("/bookings/{booking_id}/")
def update_booking(booking_id: str, payload: dict = Body(default=None)):
    payload = _require_dict(payload)
    db = SessionLocal()
    try:
        booking = _load_booking(db, booking_id)
        if "status" in payload:
            status = (payload["status"] or "").strip().lower()
            if status not in BOOKING_STATUSES:
                raise HTTPException(
                    status_code=400,
                    detail="status must be one of: "
                    + ", ".join(sorted(BOOKING_STATUSES)),
                )
            booking.status = status
        if "notes" in payload:
            booking.notes = payload["notes"]
        booking.updated_at = datetime.utcnow()
        _commit(db, what="update booking")
        db.refresh(booking)
        return _serialize_booking(booking)
    finally:
        db.close()


# ── Support tickets ───────────────────────────────────────────────────────────


def _serialize_ticket(t) -> dict:
    # `tracking_token` is the secret the customer uses to view their own ticket
    # without logging in. It is never returned, on list or detail.
    return {
        "id": str(t.id),
        "ticket_id": t.ticket_id,
        "name": t.name,
        "email": t.email,
        "category": t.category,
        "subject": t.subject,
        "message": t.message,
        "status": t.status,
        "priority": t.priority,
        "assigned_to": t.assigned_to,
        "created_at": _dj_dt(t.created_at),
        "updated_at": _dj_dt(t.updated_at),
    }


def _serialize_reply(r) -> dict:
    return {
        "id": str(r.id),
        "ticket_id": r.ticket_id,
        "author": r.author,
        "author_type": r.author_type,
        "message": r.message,
        "is_internal": r.is_internal,
        "created_at": _dj_dt(r.created_at),
    }


@router.get("/tickets/")
def list_tickets(
    limit: int = Query(default=200, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
):
    db = SessionLocal()
    try:
        rows = (
            db.query(SupportTicket)
            .order_by(SupportTicket.created_at.desc())
            .limit(limit)
            .offset(offset)
            .all()
        )
        return {"results": [_serialize_ticket(t) for t in rows]}
    finally:
        db.close()


def _load_ticket(db, ticket_pk: str) -> SupportTicket:
    try:
        row = db.query(SupportTicket).filter(SupportTicket.id == ticket_pk).first()
    except SQLAlchemyError:
        db.rollback()
        row = None
    if row is None:
        raise HTTPException(status_code=404, detail="Not found")
    return row


@router.get("/tickets/{ticket_pk}/")
def get_ticket(ticket_pk: str):
    db = SessionLocal()
    try:
        ticket = _load_ticket(db, ticket_pk)
        # Replies join on the `ticket_id` *string*, not a foreign key — same as
        # `app/api/tickets.py:163`. Not a modelling choice worth reversing here.
        replies = (
            db.query(SupportTicketReply)
            .filter(SupportTicketReply.ticket_id == ticket.ticket_id)
            .order_by(SupportTicketReply.created_at.asc())
            .all()
        )
        return {
            **_serialize_ticket(ticket),
            "replies": [_serialize_reply(r) for r in replies],
        }
    finally:
        db.close()


@router.put("/tickets/{ticket_pk}/")
@router.patch("/tickets/{ticket_pk}/")
def update_ticket(ticket_pk: str, payload: dict = Body(default=None)):
    payload = _require_dict(payload)
    db = SessionLocal()
    try:
        ticket = _load_ticket(db, ticket_pk)
        if "status" in payload:
            status = (payload["status"] or "").strip().lower()
            if status not in TICKET_STATUSES:
                raise HTTPException(
                    status_code=400,
                    detail="status must be one of: " + ", ".join(sorted(TICKET_STATUSES)),
                )
            ticket.status = status
        if "priority" in payload:
            priority = (payload["priority"] or "").strip().lower()
            if priority not in TICKET_PRIORITIES:
                raise HTTPException(
                    status_code=400,
                    detail="priority must be one of: "
                    + ", ".join(sorted(TICKET_PRIORITIES)),
                )
            ticket.priority = priority
        if "assigned_to" in payload:
            ticket.assigned_to = payload["assigned_to"] or None
        ticket.updated_at = datetime.utcnow()
        _commit(db, what="update ticket")
        db.refresh(ticket)
        return _serialize_ticket(ticket)
    finally:
        db.close()


@router.post("/tickets/{ticket_pk}/replies/", status_code=201)
def create_ticket_reply(ticket_pk: str, payload: dict = Body(default=None)):
    payload = _require_dict(payload)
    message = (payload.get("message") or "").strip()
    if not message:
        raise HTTPException(status_code=400, detail="message is required")
    db = SessionLocal()
    try:
        ticket = _load_ticket(db, ticket_pk)
        reply = SupportTicketReply(
            id=uuid.uuid4(),
            ticket_id=ticket.ticket_id,
            author=payload.get("author") or "BOOPPA Support",
            author_type=payload.get("author_type") or "agent",
            message=message,
            is_internal=bool(payload.get("is_internal", False)),
            created_at=datetime.utcnow(),
        )
        db.add(reply)
        _commit(db, what="create ticket reply")
        db.refresh(reply)
        return _serialize_reply(reply)
    finally:
        db.close()


# Included last, so `/bookings/…` and `/tickets/…` above win over `/{kind}/…`.
router.include_router(content_router)
