"""
PDPA Compliance Evidence Pack — Document Generator
Booppa Smart Care LLC · BCEP-v1.1

Generates 7 PDPA compliance documents via DeepSeek-V3.
Zero additional fixed costs — uses existing DeepSeek API budget.
Each document is ~USD 0.03-0.07 to generate. Full pack: ~USD 0.25-0.50.

IMPORTANT — LEGAL STATUS OF GENERATED DOCUMENTS:
Every document generated by this engine is a DRAFT structured by AI.
It has NO evidentiary value until:
  1. The client's authorised representative reviews and verifies the content
  2. The representative signs the document (wet signature or qualified e-signature)
  3. The signed PDF is SHA-256 hashed and anchored on the Booppa evidence chain
     (Polygon Amoy testnet by default; Polygon Mainnet when USE_MAINNET is enabled)

The blockchain timestamp proves the signed document existed at that moment.
It does NOT certify PDPA compliance. Include this disclosure in every PDF.

Stack integration: FastAPI endpoint calls generate_evidence_pack()
BCEP-v1.1 changes: added ROPA (Doc 07), added verification_required flags on all docs
"""

import json
import logging
import hashlib
from datetime import datetime, date

import httpx

from app.core.config import settings
from app.core.company import COMPANY_NAME

logger = logging.getLogger(__name__)

# ── CONFIG ───────────────────────────────────────────────────────────────
# Route through the existing DeepSeek configuration (no separate OpenAI client,
# no os.environ). Chain anchoring (Amoy testnet) lives in the Celery task.
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
MODEL             = "deepseek-chat"  # DeepSeek-V3


def _deepseek_chat(system_prompt: str, user_prompt: str) -> str:
    """Synchronous DeepSeek chat call returning raw JSON message content.

    Raises on missing key / API error so the caller records the per-document
    failure and partial packs surface cleanly.
    """
    api_key = getattr(settings, "DEEPSEEK_API_KEY", None)
    if not api_key:
        raise RuntimeError("DEEPSEEK_API_KEY is not configured")
    with httpx.Client(timeout=90.0) as client:
        resp = client.post(
            f"{DEEPSEEK_BASE_URL}/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": MODEL,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": 0.3,
                "max_tokens": 4000,
                "response_format": {"type": "json_object"},
            },
        )
    if resp.status_code >= 400:
        raise RuntimeError(f"DeepSeek API error {resp.status_code}: {resp.text}")
    return resp.json()["choices"][0]["message"]["content"]


# ── LEGAL DISCLAIMER (embedded in every document) ────────────────────────
# NOTE: Booppa has no Singapore UEN — never print one here. Anchoring is on the
# Polygon Amoy TESTNET under Lean Mode; the disclaimer says so honestly.
DRAFT_DISCLAIMER = {
    "legal_status":          "DRAFT — AI-GENERATED STRUCTURE",
    "evidentiary_value":     "NONE until client verification and signature",
    "verification_required": True,
    "verification_steps": [
        "1. Client authorised representative reviews all content for accuracy",
        "2. Representative corrects any inaccurate or missing information",
        "3. Representative signs the final PDF (wet signature or qualified e-signature)",
        "4. Signed PDF is SHA-256 hashed and anchored on the Booppa evidence chain",
        "5. The blockchain timestamp proves the document existed at that moment",
    ],
    "timestamping_note": (
        "Hashes are anchored on the Polygon Amoy testnet, which evidences "
        "proof-of-existence for tamper-checking. A testnet timestamp does not carry "
        "the settlement guarantees of a mainnet chain; for the highest legal weight, "
        "RFC 3161 timestamping from an accredited TSA is recommended."
    ),
    "not_legal_advice": (
        f"This document does not constitute legal advice and does not certify "
        f"PDPA compliance. Generated by {COMPANY_NAME}."
    ),
}

# Per-document verification notes (what specifically the client must verify)
VERIFICATION_NOTES = {
    "dpmp": [
        "Confirm DPO name and contact details are correct and the person has accepted the role",
        "Confirm the accountability structure reflects your actual organisation",
        "Confirm the management commitment statement has been read and agreed by the approver",
        "Verify the individual rights process timelines are operationally achievable",
    ],
    "ropa": [
        "CRITICAL: This is the most inspection-sensitive document. Every row must reflect actual operations.",
        "Verify each processing activity exists and is accurately described",
        "Confirm legal basis for each processing activity (do not assume 'consent' without checking)",
        "Verify retention periods are actually enforced in your systems",
        "Confirm cross-border transfer entries match your actual hosting and vendor geography",
        "Add any processing activities missing from the AI-generated list",
        "Remove any processing activities that do not apply to your organisation",
    ],
    "data_inventory": [
        "Verify each data category exists in your actual systems",
        "Confirm storage locations are accurate (especially cloud region)",
        "Verify retention periods are enforced and destruction is actually performed",
    ],
    "vendor_register": [
        "Verify each vendor listed actually processes personal data on your behalf",
        "Confirm DPA status for each vendor — do not mark 'In place' without checking",
        "Add vendors not listed that handle personal data (check bank transfers, HR tools, etc.)",
        "For cross-border transfers: confirm a Transfer Impact Assessment is in place",
    ],
    "breach_runbook": [
        "Replace all role names with actual named individuals and their contact details",
        "Verify the escalation chain reflects your actual organisational structure",
        "Test the notification workflow at least once before signing",
        "Confirm the PDPC notification template URL is current: https://www.pdpc.gov.sg/report-a-data-breach",
    ],
    "training": [
        "CRITICAL: Training log entries must reflect ACTUAL training that occurred",
        "Do not sign this document unless real training has been conducted",
        "Fill in actual employee names, dates, and completion records before signing",
        "If no training has occurred yet, this document serves as the programme plan only",
    ],
    "review_log": [
        "Completed review entries must reflect ACTUAL reviews that were conducted",
        "Do not backdate entries — dates must be accurate",
        "The first entry should reflect the first real review after this document is signed",
        "Each completed review should be re-anchored on the Booppa evidence chain individually",
    ],
}

# ── SYSTEM PROMPT ────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a Singapore PDPA compliance expert generating formal 
compliance documentation for organisations. 

Rules:
- All documents must reference specific PDPA sections (e.g. PDPA §11, §24, §25, §26)
- Language: formal English, professional tone
- Every document must include: organisation name, date, version number, next review date
- Do NOT include placeholder text like [INSERT HERE] — generate realistic, specific content
- Output ONLY valid JSON, no markdown, no preamble
- Base all content on the specific organisation data provided — not generic templates
- When OBSERVED EVIDENCE from a website/PDPA scan is provided, reflect it in the
  document: acknowledge gaps the scan surfaced (e.g. missing cookie-consent banner,
  no HTTPS, absent privacy policy) and record them as open items / remediation
  actions rather than asserting compliance the evidence contradicts
"""


def _evidence_context(scan_evidence: dict | None) -> str:
    """Render observed website/PDPA-scan signals into a compact grounding block
    appended to the relevant prompts. Returns '' when no evidence is available so
    intake-only generation is unchanged.
    """
    if not scan_evidence or not isinstance(scan_evidence, dict):
        return ""

    lines: list[str] = []

    web = scan_evidence.get("website_scan") or {}
    if isinstance(web, dict) and web:
        url = web.get("website_url", "the website")
        score = web.get("score")
        level = web.get("risk_level")
        header = f"Website scan of {url}"
        if score is not None:
            header += f" — risk score {score}/100 ({level})" if level else f" — risk score {score}/100"
        lines.append(header + ":")
        findings = web.get("findings") or []
        if not findings and web.get("free_finding"):
            findings = [web["free_finding"]]
        for f in findings[:12]:
            if not isinstance(f, dict):
                continue
            sev = f.get("severity", "")
            title = f.get("title", "")
            cat = f.get("category", "")
            lines.append(f"  - [{sev}] {title}{f' ({cat})' if cat else ''}")
        if not findings:
            lines.append("  - No specific findings returned by the scanner.")

    pdpa = scan_evidence.get("pdpa_report") or {}
    if isinstance(pdpa, dict) and pdpa:
        pf = pdpa.get("findings") or []
        if pf:
            lines.append("Prior PDPA Snapshot findings:")
            for f in pf[:12]:
                if isinstance(f, dict):
                    lines.append(f"  - [{f.get('severity','')}] {f.get('title','')}")
                elif isinstance(f, str):
                    lines.append(f"  - {f}")

    if not lines:
        return ""

    return (
        "\n\nOBSERVED EVIDENCE (incorporate into this document; flag gaps as open "
        "remediation items — do NOT claim compliance the evidence contradicts):\n"
        + "\n".join(lines)
    )

# ── DOCUMENT PROMPTS ─────────────────────────────────────────────────────

def _prompt_dpmp(intake: dict) -> str:
    return f"""Generate a complete Data Protection Management Programme (DPMP) for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Employees: {intake['employee_count']}
DPO Name: {intake.get('dpo_name', 'To be designated')}
DPO Email: {intake.get('dpo_email', 'dpo@' + intake.get('domain', 'company.com.sg'))}
Senior Approver: {intake['approver_name']}, {intake['approver_role']}
Data types processed: {', '.join(intake['data_types'])}
Assessment date: {date.today().isoformat()}

Return JSON with this exact structure:
{{
  "document_title": "Data Protection Management Programme",
  "organisation": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§11", "§12", "§13"],
  "sections": {{
    "policy_statement": "...",
    "scope": "...",
    "dpo_designation": {{
      "name": "...",
      "email": "...",
      "responsibilities": ["...", "..."]
    }},
    "accountability_structure": {{
      "board_level": "...",
      "management_level": "...",
      "operational_level": "..."
    }},
    "individual_rights_process": {{
      "access_requests": "...",
      "correction_requests": "...",
      "withdrawal_of_consent": "...",
      "response_timeline": "10 business days"
    }},
    "training_commitment": "...",
    "review_cycle": "Annual",
    "management_commitment_statement": "..."
  }}
}}"""


def _prompt_ropa(intake: dict) -> str:
    """
    ROPA — Record of Processing Activities.
    This is the most critical document for PDPC inspections.
    Equivalent to GDPR Art. 30 under Singapore PDPA framework.
    """
    systems_str = ', '.join(intake.get('systems', ['CRM', 'Email', 'HR System']))
    return f"""Generate a detailed Record of Processing Activities (ROPA) for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Employees: {intake['employee_count']}
DPO: {intake.get('dpo_name', 'To be designated')} ({intake.get('dpo_email', '')})
Systems in use: {systems_str}
Customer types: {', '.join(intake.get('customer_types', ['B2B clients']))}
Data types: {', '.join(intake['data_types'])}
Cloud provider: {intake.get('cloud_provider', 'AWS')}
Other markets: {intake.get('other_markets', 'Singapore only')}
Assessment date: {date.today().isoformat()}

The ROPA must document EVERY processing activity — not just categories.
Each row is one specific processing operation (e.g. "Sending marketing emails" is separate from "Processing customer payments").

Return JSON with this exact structure:
{{
  "document_title": "Record of Processing Activities (ROPA)",
  "organisation": "...",
  "uen": "...",
  "dpo_name": "...",
  "dpo_email": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§11", §18", "§24", "§25", "§26"],
  "processing_activities": [
    {{
      "activity_id": "PA-001",
      "activity_name": "Customer onboarding and account creation",
      "department": "Sales / Operations",
      "data_controller": "{intake['org_name']}",
      "purpose": "To create and manage customer accounts and deliver contracted services",
      "legal_basis": "Contractual necessity (PDPA §13 — consent for collection, use and disclosure)",
      "data_categories": ["Full name", "Email address", "Phone number", "Company name", "Job title"],
      "special_categories": [],
      "data_subjects": "Business clients and their authorised representatives",
      "volume_estimate": "...",
      "source_of_data": "Direct collection via onboarding form",
      "recipients": ["Internal: Sales team, Finance team", "External: Xero (invoicing)"],
      "cross_border_transfer": false,
      "transfer_destination": null,
      "transfer_mechanism": null,
      "storage_system": "...",
      "storage_location": "Singapore / AWS ap-southeast-1",
      "retention_period": "7 years from end of contract",
      "retention_basis": "Legal obligation (IRAS record-keeping requirements)",
      "destruction_method": "Secure deletion from all systems",
      "security_measures": ["Access control", "Encryption at rest", "Audit logging"],
      "last_reviewed": "YYYY-MM-DD",
      "review_notes": ""
    }}
  ],
  "cross_border_transfers_summary": [
    {{
      "destination_country": "...",
      "vendor": "...",
      "data_transferred": "...",
      "mechanism": "Standard contractual clauses / Adequacy / Consent",
      "tia_in_place": false,
      "tia_date": null
    }}
  ],
  "ropa_owner": "DPO",
  "last_full_review": "YYYY-MM-DD",
  "next_full_review": "YYYY-MM-DD"
}}

Generate at least 8 realistic processing activities specific to a {intake['sector']} company 
using {systems_str}. Cover: customer management, employee data, marketing, finance, 
IT security/access logs, and any sector-specific activities.
Each activity must be genuinely distinct — not just category variations."""


def _prompt_data_inventory(intake: dict) -> str:
    systems_str = ', '.join(intake.get('systems', ['CRM', 'Email', 'HR System']))
    return f"""Generate a Data Inventory and Retention Schedule for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Systems in use: {systems_str}
Customer types: {', '.join(intake.get('customer_types', ['B2B clients']))}
Cloud provider: {intake.get('cloud_provider', 'AWS')}
Assessment date: {date.today().isoformat()}

Return JSON with this exact structure:
{{
  "document_title": "Data Inventory and Retention Schedule",
  "organisation": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§25", "§18"],
  "inventory": [
    {{
      "category": "Customer Personal Data",
      "data_elements": ["name", "email", "phone", "address"],
      "source": "Direct collection via website/onboarding",
      "purpose": "Service delivery and communication",
      "legal_basis": "Consent / Contractual necessity",
      "data_owner": "...",
      "storage_system": "...",
      "storage_location": "Singapore / AWS ap-southeast-1",
      "retention_period": "7 years from end of relationship",
      "destruction_method": "Secure deletion / shredding",
      "review_date": "YYYY-MM-DD"
    }}
  ],
  "destruction_log_template": {{
    "fields": ["date", "category", "volume", "method", "authorised_by", "witness"],
    "frequency": "Quarterly review"
  }},
  "scheduled_review": {{
    "frequency": "Annual",
    "next_review": "YYYY-MM-DD",
    "responsible": "DPO"
  }}
}}

Generate at least 6 realistic inventory entries based on the sector and systems provided."""


def _prompt_vendor_register(intake: dict) -> str:
    systems_str = json.dumps(intake.get('systems', ['AWS', 'Google Workspace', 'Stripe']))
    return f"""Generate a Third-Party Processor Register and DPA Checklist for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Systems/vendors in use: {systems_str}
Cloud provider: {intake.get('cloud_provider', 'AWS')}
Primary markets: Singapore{', ' + intake.get('other_markets', '') if intake.get('other_markets') else ''}
Assessment date: {date.today().isoformat()}

Return JSON with this exact structure:
{{
  "document_title": "Third-Party Processor Register and DPA Checklist",
  "organisation": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§26", "§24"],
  "vendors": [
    {{
      "vendor_name": "Amazon Web Services",
      "role": "Data Processor",
      "data_processed": ["customer data", "application data"],
      "processing_purpose": "Cloud hosting and storage",
      "server_location": "Singapore (ap-southeast-1)",
      "cross_border_transfer": false,
      "dpa_status": "In place",
      "dpa_reference": "AWS Data Processing Addendum - https://aws.amazon.com/agreement/",
      "transfer_mechanism": "N/A - Singapore region",
      "risk_level": "Medium",
      "last_reviewed": "YYYY-MM-DD",
      "action_required": null
    }}
  ],
  "gap_register": [
    {{
      "vendor": "...",
      "gap": "DPA not signed",
      "action": "Request DPA from vendor",
      "deadline": "YYYY-MM-DD",
      "owner": "DPO",
      "status": "Open"
    }}
  ],
  "transfer_impact_assessment_template": {{
    "applicable_when": "Transfer of personal data outside Singapore",
    "assessment_fields": ["destination_country", "legal_framework", "safeguards", "residual_risk", "approval_date"]
  }}
}}

Generate at least 5 realistic vendor entries. Include gaps where DPAs are typically missing."""


def _prompt_breach_runbook(intake: dict) -> str:
    return f"""Generate a Data Breach Response Runbook for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Employees: {intake['employee_count']}
DPO: {intake.get('dpo_name', 'DPO')} ({intake.get('dpo_email', 'dpo@company.com.sg')})
IT Contact: {intake.get('it_contact', 'IT Manager')}
Senior Approver: {intake['approver_name']}, {intake['approver_role']}
Assessment date: {date.today().isoformat()}

Return JSON with this exact structure:
{{
  "document_title": "Data Breach Response Runbook",
  "organisation": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§26B", "§26C", "§26D"],
  "escalation_chain": [
    {{"role": "Any staff member", "action": "Report to DPO immediately", "timeline": "Within 1 hour of discovery"}},
    {{"role": "DPO", "action": "Assess breach severity", "timeline": "Within 3 hours"}},
    {{"role": "DPO + Senior Management", "action": "Decide on notification", "timeline": "Within 24 hours"}},
    {{"role": "DPO", "action": "Notify PDPC if notifiable", "timeline": "Within 3 calendar days"}}
  ],
  "notifiability_assessment": {{
    "threshold_scale": "500 or more individuals affected",
    "threshold_harm": "Likely to result in significant harm",
    "significant_harm_examples": ["identity theft", "financial loss", "physical harm", "reputational damage"],
    "assessment_questions": ["How many individuals affected?", "What type of data?", "Is there evidence of misuse?"]
  }},
  "pdpc_notification_template": {{
    "submission_url": "https://www.pdpc.gov.sg/report-a-data-breach",
    "required_fields": ["organisation_name", "breach_date", "discovery_date", "data_types", "number_affected", "cause", "remediation_steps"],
    "sample_notification": "..."
  }},
  "individual_notification_template": {{
    "trigger": "When significant harm is likely to affected individuals",
    "channel": "Email / Phone / Written letter",
    "sample_text": "..."
  }},
  "containment_steps": ["...", "..."],
  "evidence_preservation": ["...", "..."],
  "post_breach_review_template": {{
    "fields": ["breach_summary", "root_cause", "lessons_learned", "process_changes", "completion_date"],
    "deadline": "Within 30 days of breach resolution"
  }},
  "simulation_log_template": {{
    "recommended_frequency": "Annual",
    "fields": ["simulation_date", "scenario", "participants", "findings", "action_items"],
    "next_simulation": "YYYY-MM-DD"
  }}
}}"""


def _prompt_training_register(intake: dict) -> str:
    return f"""Generate a Staff Training Register and PDPA Training Programme for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Employees: {intake['employee_count']}
DPO: {intake.get('dpo_name', 'DPO')}
Training start date: {date.today().isoformat()}

Return JSON with this exact structure:
{{
  "document_title": "Staff Training Register and Completion Evidence",
  "organisation": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§11", "§24"],
  "training_programme": {{
    "module_1": {{
      "title": "PDPA Fundamentals",
      "duration": "45 minutes",
      "content": ["What is personal data", "The 9 data protection obligations", "Consent requirements", "Individual rights"],
      "frequency": "Annual + new joiners within 30 days"
    }},
    "module_2": {{
      "title": "Data Handling Procedures",
      "duration": "30 minutes",
      "content": ["How to handle customer data", "Clean desk policy", "Email and file security", "Access control"],
      "frequency": "Annual"
    }},
    "module_3": {{
      "title": "Breach Reporting",
      "duration": "20 minutes",
      "content": ["What is a data breach", "How to recognise a breach", "Who to report to", "What not to do"],
      "frequency": "Annual"
    }},
    "module_4": {{
      "title": "NRIC Compliance (deadline 31 Dec 2026)",
      "duration": "20 minutes",
      "content": ["PDPC Advisory on NRIC", "When collection is permitted", "Existing NRIC data remediation", "Deadline obligations"],
      "frequency": "Once — mandatory before Dec 2026"
    }}
  }},
  "completion_register": {{
    "note": "POPULATE WITH ACTUAL STAFF TRAINING RECORDS — do not sign until real training has occurred",
    "fields": ["employee_name", "employee_id", "department", "module", "completion_date", "score", "certificate_id"],
    "entries": []
  }},
  "recurring_schedule": {{
    "annual_refresh": "Every 12 months from initial training",
    "new_joiner": "Within 30 days of start date",
    "trigger_events": ["New PDPC guidance issued", "Breach incident", "Significant system change"]
  }},
  "assessment_questions": [
    {{"question": "Under PDPA, personal data refers to:", "options": ["A) Any business data", "B) Data that identifies an individual", "C) Only NRIC numbers", "D) Financial records only"], "answer": "B"}},
    {{"question": "If you suspect a data breach, you should:", "options": ["A) Fix it yourself quietly", "B) Wait to see if it gets worse", "C) Report to DPO immediately", "D) Email customers first"], "answer": "C"}}
  ]
}}"""


def _prompt_review_log(intake: dict) -> str:
    return f"""Generate a Periodic Security Review Log with pre-seeded schedule for:

Organisation: {intake['org_name']}
Sector: {intake['sector']}
Systems: {', '.join(intake.get('systems', ['CRM', 'Email', 'Cloud Storage']))}
DPO: {intake.get('dpo_name', 'DPO')}
IT Contact: {intake.get('it_contact', 'IT Manager')}
Start date: {date.today().isoformat()}

Return JSON with this exact structure:
{{
  "document_title": "Periodic Security Review Log",
  "organisation": "...",
  "version": "1.0",
  "effective_date": "YYYY-MM-DD",
  "next_review_date": "YYYY-MM-DD",
  "pdpa_references": ["§24"],
  "review_schedule": [
    {{
      "review_type": "Access Control Review",
      "frequency": "Quarterly",
      "scope": "Review who has access to personal data systems. Remove stale accounts. Verify role-based access.",
      "responsible": "IT Manager + DPO",
      "next_due": "YYYY-MM-DD",
      "estimated_duration": "2 hours"
    }},
    {{
      "review_type": "Vulnerability Assessment",
      "frequency": "Semi-annual",
      "scope": "Scan all systems handling personal data for known vulnerabilities. Patch critical findings within 14 days.",
      "responsible": "IT Manager",
      "next_due": "YYYY-MM-DD",
      "estimated_duration": "4 hours"
    }},
    {{
      "review_type": "Data Protection Audit",
      "frequency": "Annual",
      "scope": "Full review of DPMP, ROPA, data inventory, vendor register, training records, breach procedures.",
      "responsible": "DPO",
      "next_due": "YYYY-MM-DD",
      "estimated_duration": "1 day"
    }},
    {{
      "review_type": "Privacy Policy Review",
      "frequency": "Annual",
      "scope": "Verify privacy policy reflects current data processing. Update for any regulatory changes.",
      "responsible": "DPO + Legal",
      "next_due": "YYYY-MM-DD",
      "estimated_duration": "3 hours"
    }}
  ],
  "completed_reviews": [],
  "review_template": {{
    "fields": ["review_type", "date_conducted", "reviewer", "scope_covered", "findings", "risk_rating", "remediation_actions", "deadline", "status", "sign_off"],
    "risk_ratings": ["Low", "Medium", "High", "Critical"]
  }},
  "gap_register": {{
    "description": "Open findings from reviews requiring remediation",
    "fields": ["finding_id", "review_date", "finding", "risk", "owner", "deadline", "status"]
  }}
}}"""


# ── DRAFT STATUS WRAPPER ─────────────────────────────────────────────────

def _wrap_with_draft_status(doc: dict, doc_type: str) -> dict:
    """
    Wraps every generated document with:
    - Legal status: DRAFT
    - Verification required flag
    - Document-specific verification checklist
    - Timestamping guidance

    This wrapper must NOT be removed before client delivery.
    The signed + verified version replaces this wrapper after client sign-off.
    """
    return {
        "_booppa_draft_status": {
            **DRAFT_DISCLAIMER,
            "document_type":           doc_type,
            "generated_at":            datetime.utcnow().isoformat() + "Z",
            "client_verification_checklist": VERIFICATION_NOTES.get(doc_type, []),
            "signature_required_from": "Authorised representative of the organisation",
            "anchor_network":          settings.active_polygon_network_name,
        },
        **doc,
    }


# ── CORE GENERATOR ───────────────────────────────────────────────────────

def generate_document(doc_type: str, intake: dict, scan_evidence: dict | None = None) -> dict:
    """
    Generate a single compliance document via DeepSeek-V3.
    Returns parsed JSON dict wrapped with draft status.

    `scan_evidence` (optional) carries observed website/PDPA-scan signals; when
    present its grounding block is appended to the documents where observed
    evidence is most material. Passing None preserves intake-only behaviour.
    """
    prompts = {
        "dpmp":            _prompt_dpmp(intake),
        "ropa":            _prompt_ropa(intake),
        "data_inventory":  _prompt_data_inventory(intake),
        "vendor_register": _prompt_vendor_register(intake),
        "breach_runbook":  _prompt_breach_runbook(intake),
        "training":        _prompt_training_register(intake),
        "review_log":      _prompt_review_log(intake),
    }

    if doc_type not in prompts:
        raise ValueError(f"Unknown document type: {doc_type}")

    # Ground the CUSTOMER's real UEN so the AI never invents one (and Booppa's
    # non-existent UEN never appears).
    uen = (intake.get("uen") or "").strip()
    if uen:
        uen_ctx = (
            f"\n\nThe organisation's Singapore UEN (Business Registration No.) is "
            f"EXACTLY: {uen}. Use this exact UEN wherever a UEN field appears. "
            "Never invent a different UEN."
        )
    else:
        uen_ctx = (
            "\n\nNo UEN was provided. Leave any UEN field as 'Not provided' — "
            "do NOT invent one."
        )

    # Ground the evidence-sensitive documents in observed scan signals. The
    # other documents (training, breach templates) are intake-driven only.
    evidence_ctx = ""
    if doc_type in ("dpmp", "data_inventory", "vendor_register", "breach_runbook", "review_log"):
        evidence_ctx = _evidence_context(scan_evidence)

    raw = _deepseek_chat(SYSTEM_PROMPT, prompts[doc_type] + uen_ctx + evidence_ctx)
    doc = json.loads(raw)
    return _wrap_with_draft_status(doc, doc_type)


def generate_evidence_pack(intake: dict, scan_evidence: dict | None = None) -> dict:
    """
    Generate all 7 documents for an Evidence Pack (BCEP-v1.1).

    Document order:
      01 — DPMP (Data Protection Management Programme)
      02 — ROPA (Record of Processing Activities)  ← NEW in v1.1
      03 — Data Inventory & Retention Schedule
      04 — Third-Party Processor Register & DPA Checklist
      05 — Data Breach Response Runbook
      06 — Staff Training Register
      07 — Periodic Security Review Log

    intake = {
        "org_name": "Cordeos Pte Ltd",
        "sector": "IT Services",
        "employee_count": "11-50",
        "domain": "cordeos.com.sg",
        "dpo_name": "Jonathan Lee",
        "dpo_email": "dpo@cordeos.com.sg",
        "approver_name": "Michael Tan",
        "approver_role": "Managing Director",
        "data_types": ["customer data", "employee data", "vendor data"],
        "systems": ["AWS", "Google Workspace", "HubSpot", "Xero"],
        "cloud_provider": "AWS",
        "customer_types": ["B2B corporate clients"],
        "it_contact": "IT Manager",
        "other_markets": ""
    }
    """
    doc_types = [
        "dpmp",
        "ropa",           # NEW — Record of Processing Activities
        "data_inventory",
        "vendor_register",
        "breach_runbook",
        "training",
        "review_log",
    ]

    pack = {
        "pack_id":        _generate_pack_id(intake["org_name"]),
        "organisation":   intake["org_name"],
        "uen":            (intake.get("uen") or "").strip() or "Not provided",
        "generated_at":   datetime.utcnow().isoformat() + "Z",
        "framework":      "BCEP-v1.1",
        "status":         "generated",
        "legal_status":   "DRAFT — requires client verification and signature before evidentiary use",
        "evidence_grounded": bool(scan_evidence),
        "documents":      {},
        "hashes":         {},
        "errors":         [],
    }

    for doc_type in doc_types:
        # Retry once in-place: a transient AI/JSON-parse failure on a single doc
        # should self-heal here rather than fail the whole pack downstream (which
        # would regenerate AND re-anchor all 7 docs, costing gas). The pack is
        # sold as SEVEN documents, so a doc left in `errors` is caught by the
        # completeness gate in the fulfillment task.
        last_err: Exception | None = None
        for attempt in range(2):
            try:
                print(f"  Generating {doc_type}..." + (" (retry)" if attempt else ""))
                doc      = generate_document(doc_type, intake, scan_evidence)
                doc_json = json.dumps(doc, sort_keys=True)
                doc_hash = hashlib.sha256(doc_json.encode()).hexdigest()

                pack["documents"][doc_type] = doc
                pack["hashes"][doc_type]    = doc_hash
                last_err = None
                break
            except Exception as e:
                last_err = e
                print(f"  ERROR on {doc_type} (attempt {attempt + 1}): {e}")
        if last_err is not None:
            pack["errors"].append({"doc_type": doc_type, "error": str(last_err)})

    # Master hash over all 7 document hashes
    master_input     = json.dumps(pack["hashes"], sort_keys=True)
    pack["master_hash"] = hashlib.sha256(master_input.encode()).hexdigest()

    return pack


def _generate_pack_id(org_name: str) -> str:
    ts   = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    slug = org_name.upper().replace(" ", "")[:8]
    return f"BCEP-{slug}-{ts}"
