"""Initial tables

Revision ID: 0dd4e428633f
Revises:
Create Date: 2026-01-14 00:09:02.489285+07:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0dd4e428633f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("ip_anonymized", sa.String(length=64), nullable=True),
        sa.Column("consent_status", sa.String(length=50), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_logs_consent_status"),
        "consent_logs",
        ["consent_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consent_logs_timestamp"),
        "consent_logs",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("framework", sa.String(length=100), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("company_website", sa.String(length=500), nullable=True),
        sa.Column("assessment_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("audit_hash", sa.String(length=64), nullable=True),
        sa.Column("tx_hash", sa.String(length=66), nullable=True),
        sa.Column("s3_url", sa.Text(), nullable=True),
        sa.Column("file_key", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("ai_narrative", sa.Text(), nullable=True),
        sa.Column("ai_model_used", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reports_owner_id"), "reports", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_reports_status"), "reports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_reports_tx_hash"), "reports", ["tx_hash"], unique=False
    )
    op.create_table(
        "task_locks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_locks_task_id"), "task_locks", ["task_id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_task_locks_task_id"), table_name="task_locks")
    op.drop_table("task_locks")
    op.drop_index(op.f("ix_reports_tx_hash"), table_name="reports")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_owner_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_consent_logs_timestamp"), table_name="consent_logs")
    op.drop_index(
        op.f("ix_consent_logs_consent_status"), table_name="consent_logs"
    )
    op.drop_table("consent_logs")
    # ### end Alembic commands ###
