"""v6_os_infrastructure

Revision ID: 6ae5998fc1ab
Revises: 2026_02_07_1500
Create Date: 2026-02-21 11:05:04.423065+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae5998fc1ab'
down_revision = '2026_02_07_1500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystem_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sector_density', sa.JSON(), nullable=True),
    sa.Column('total_vendors', sa.Integer(), nullable=True),
    sa.Column('active_vendors', sa.Integer(), nullable=True),
    sa.Column('avg_vendor_score', sa.Float(), nullable=True),
    sa.Column('total_enterprises', sa.Integer(), nullable=True),
    sa.Column('active_procurements', sa.Integer(), nullable=True),
    sa.Column('gov_activity', sa.Integer(), nullable=True),
    sa.Column('triggers_24h', sa.Integer(), nullable=True),
    sa.Column('avg_trigger_score', sa.Float(), nullable=True),
    sa.Column('procurement_heatmap', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecosystem_index_date'), 'ecosystem_index', ['date'], unique=True)
    op.create_table('enterprise_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('organization_type', sa.Enum('GOVERNMENT', 'GLC', 'CORPORATE', 'SME', 'UNKNOWN', name='organizationtype'), nullable=True),
    sa.Column('industry_inference', sa.String(length=255), nullable=True),
    sa.Column('visit_frequency', sa.Integer(), nullable=True),
    sa.Column('unique_vendors_viewed', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('behavioral_score', sa.Integer(), nullable=True),
    sa.Column('procurement_intent_score', sa.Integer(), nullable=True),
    sa.Column('is_government', sa.Boolean(), nullable=True),
    sa.Column('active_procurement', sa.Boolean(), nullable=True),
    sa.Column('procurement_window_start', sa.DateTime(), nullable=True),
    sa.Column('procurement_window_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_enterprise_profiles_active_procurement'), 'enterprise_profiles', ['active_procurement'], unique=False)
    op.create_index(op.f('ix_enterprise_profiles_behavioral_score'), 'enterprise_profiles', ['behavioral_score'], unique=False)
    op.create_index(op.f('ix_enterprise_profiles_organization_type'), 'enterprise_profiles', ['organization_type'], unique=False)
    op.create_table('governance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('verify_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_records_correlation_id'), 'governance_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_governance_records_timestamp'), 'governance_records', ['timestamp'], unique=False)
    op.create_table('lead_captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('uen', sa.String(length=50), nullable=True),
    sa.Column('avg_tender_value', sa.Integer(), nullable=True),
    sa.Column('tenders_per_year', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Integer(), nullable=True),
    sa.Column('lost_revenue', sa.Integer(), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_captures_converted'), 'lead_captures', ['converted'], unique=False)
    op.create_index(op.f('ix_lead_captures_email'), 'lead_captures', ['email'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_type'), 'activity_logs', ['type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('domain_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('unique_proofs', sa.Integer(), nullable=True),
    sa.Column('unique_vendors', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_government', sa.Boolean(), nullable=True),
    sa.Column('enterprise_triggered', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_activities_domain'), 'domain_activities', ['domain'], unique=True)
    op.create_index(op.f('ix_domain_activities_is_government'), 'domain_activities', ['is_government'], unique=False)
    op.create_index(op.f('ix_domain_activities_last_seen'), 'domain_activities', ['last_seen'], unique=False)
    op.create_table('enterprise_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('triggered', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='leadpriority'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'MEETING_SCHEDULED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', name='leadstatus'), nullable=True),
    sa.Column('deal_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_enterprise_leads_priority'), 'enterprise_leads', ['priority'], unique=False)
    op.create_index(op.f('ix_enterprise_leads_score'), 'enterprise_leads', ['score'], unique=False)
    op.create_index(op.f('ix_enterprise_leads_status'), 'enterprise_leads', ['status'], unique=False)
    op.create_table('gebiz_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('tender_id', sa.String(length=255), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gebiz_activities_created_at'), 'gebiz_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_gebiz_activities_domain'), 'gebiz_activities', ['domain'], unique=False)
    op.create_table('vendor_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('recency_score', sa.Integer(), nullable=True),
    sa.Column('procurement_interest_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('last_calculation', sa.DateTime(), nullable=True),
    sa.Column('calculation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendor_scores_total_score'), 'vendor_scores', ['total_score'], unique=False)
    op.create_table('vendor_sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_sectors_sector'), 'vendor_sectors', ['sector'], unique=False)
    op.create_table('verify_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Integer(), nullable=True),
    sa.Column('verification_level', sa.Enum('BASIC', 'STANDARD', 'PREMIUM', 'GOVERNMENT', name='verificationlevel'), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('ACTIVE', 'EXPIRED', 'UNDER_REVIEW', 'SUSPENDED', name='lifecyclestatus'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verify_records_lifecycle_status'), 'verify_records', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_verify_records_vendor_id'), 'verify_records', ['vendor_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW', name='meetingstatus'), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['enterprise_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verify_id', sa.UUID(), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['verify_id'], ['verify_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofs_hash'), 'proofs', ['hash'], unique=True)
    op.create_index(op.f('ix_proofs_verify_id'), 'proofs', ['verify_id'], unique=False)
    op.create_table('proof_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verify_id', sa.UUID(), nullable=True),
    sa.Column('proof_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=255), nullable=True),
    sa.Column('org', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verify_id'], ['verify_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_views_created_at'), 'proof_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_proof_views_domain'), 'proof_views', ['domain'], unique=False)
    op.create_index(op.f('ix_proof_views_verify_id'), 'proof_views', ['verify_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('uen', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('temp_password', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['uen'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'temp_password')
    op.drop_column('users', 'uen')
    op.drop_column('users', 'company')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_proof_views_verify_id'), table_name='proof_views')
    op.drop_index(op.f('ix_proof_views_domain'), table_name='proof_views')
    op.drop_index(op.f('ix_proof_views_created_at'), table_name='proof_views')
    op.drop_table('proof_views')
    op.drop_index(op.f('ix_proofs_verify_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_hash'), table_name='proofs')
    op.drop_table('proofs')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_verify_records_vendor_id'), table_name='verify_records')
    op.drop_index(op.f('ix_verify_records_lifecycle_status'), table_name='verify_records')
    op.drop_table('verify_records')
    op.drop_index(op.f('ix_vendor_sectors_sector'), table_name='vendor_sectors')
    op.drop_table('vendor_sectors')
    op.drop_index(op.f('ix_vendor_scores_total_score'), table_name='vendor_scores')
    op.drop_table('vendor_scores')
    op.drop_index(op.f('ix_gebiz_activities_domain'), table_name='gebiz_activities')
    op.drop_index(op.f('ix_gebiz_activities_created_at'), table_name='gebiz_activities')
    op.drop_table('gebiz_activities')
    op.drop_index(op.f('ix_enterprise_leads_status'), table_name='enterprise_leads')
    op.drop_index(op.f('ix_enterprise_leads_score'), table_name='enterprise_leads')
    op.drop_index(op.f('ix_enterprise_leads_priority'), table_name='enterprise_leads')
    op.drop_table('enterprise_leads')
    op.drop_index(op.f('ix_domain_activities_last_seen'), table_name='domain_activities')
    op.drop_index(op.f('ix_domain_activities_is_government'), table_name='domain_activities')
    op.drop_index(op.f('ix_domain_activities_domain'), table_name='domain_activities')
    op.drop_table('domain_activities')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_lead_captures_email'), table_name='lead_captures')
    op.drop_index(op.f('ix_lead_captures_converted'), table_name='lead_captures')
    op.drop_table('lead_captures')
    op.drop_index(op.f('ix_governance_records_timestamp'), table_name='governance_records')
    op.drop_index(op.f('ix_governance_records_correlation_id'), table_name='governance_records')
    op.drop_table('governance_records')
    op.drop_index(op.f('ix_enterprise_profiles_organization_type'), table_name='enterprise_profiles')
    op.drop_index(op.f('ix_enterprise_profiles_behavioral_score'), table_name='enterprise_profiles')
    op.drop_index(op.f('ix_enterprise_profiles_active_procurement'), table_name='enterprise_profiles')
    op.drop_table('enterprise_profiles')
    op.drop_index(op.f('ix_ecosystem_index_date'), table_name='ecosystem_index')
    op.drop_table('ecosystem_index')
    # ### end Alembic commands ###
