"""Bundle fulfillment: fan-out shape via BUNDLE_COMPONENTS."""
import pytest

from tests.fixtures.product_catalog import BUNDLES, sku_id
from tests.fixtures.stripe_events import wrap_event


@pytest.mark.parametrize("case", BUNDLES, ids=[sku_id(c) for c in BUNDLES])
def test_bundle_queues_fulfill_bundle_task_with_components(
    case, client, post_webhook, stripe_session_factory, mocker
):
    """Each bundle should be passed verbatim to fulfill_bundle_task.delay."""
    fake_task = mocker.patch("app.workers.tasks.fulfill_bundle_task")
    fake_task.delay = mocker.MagicMock()

    session = stripe_session_factory(case.product_type)
    resp = post_webhook(wrap_event(session))
    assert resp.status_code == 200

    fake_task.delay.assert_called_once()
    kwargs = fake_task.delay.call_args.kwargs
    assert kwargs["product_type"] == case.product_type
    assert kwargs["customer_email"] == session["customer_email"]
    assert kwargs["session_id"] == session["id"]
    md = kwargs["metadata"]
    assert md["company_name"] == "Test Co"
    assert md["vendor_url"] == "https://example.test"


def test_bundle_component_definitions_intact():
    """Sanity: BUNDLE_COMPONENTS contents match the product spec.

    These numbers come from the canonical product spec in memory:
      - vendor_trust_pack: VP + PDPA + 2× notarization
      - rfp_accelerator:    VP + PDPA + 2× notarization + rfp_express
      - enterprise_bid_kit: VP + PDPA + 7× notarization + rfp_complete
      - compliance_evidence_pack: PDPA + 1× notarization + rfp_complete + cover_sheet
    """
    from app.api.stripe_webhook import BUNDLE_COMPONENTS

    vtp = BUNDLE_COMPONENTS["vendor_trust_pack"]
    assert vtp["vendor_proof"] and vtp["pdpa"] and vtp["notarization_count"] == 2
    assert vtp["rfp"] is None

    acc = BUNDLE_COMPONENTS["rfp_accelerator"]
    assert acc["rfp"] == "rfp_express" and acc["notarization_count"] == 2

    ebk = BUNDLE_COMPONENTS["enterprise_bid_kit"]
    assert ebk["rfp"] == "rfp_complete" and ebk["notarization_count"] == 7

    cep = BUNDLE_COMPONENTS["compliance_evidence_pack"]
    assert cep.get("cover_sheet") is True and cep["rfp"] == "rfp_complete"


def test_cover_sheet_sweep_fires_for_owed_buyer(test_db, mocker):
    """Backstop: a buyer still owed a cover sheet (PDPA + RFP both done,
    pending_cover_sheet=True) gets it generated by the hourly sweep even if the
    inline trigger was missed — the exact gap the forensic audit caught where
    one buyer's 3-doc bundle never delivered its cover sheet.
    """
    from datetime import datetime, timezone
    from app.core.models import User, Report

    fake_cs = mocker.patch("app.workers.tasks.fulfill_cover_sheet_task")
    fake_cs.apply_async = mocker.MagicMock()

    email = "cep+sweep@booppa.io"
    user = User(
        email=email,
        hashed_password="not-a-real-hash",
        role="VENDOR",
        plan="free",
        company="Sweep Co",
        website="https://example.test",
        pending_cover_sheet=True,
        compliance_evidence_rfp_ready=True,  # RFP kit delivered
    )
    test_db.add(user)
    test_db.commit()
    test_db.refresh(user)

    # PDPA scan completed — the other required input for the cover sheet.
    test_db.add(Report(
        owner_id=user.id,
        framework="pdpa_quick_scan",
        company_name="Sweep Co",
        company_website="https://example.test",
        status="completed",
        assessment_data={"overall_risk_score": 46},
        completed_at=datetime.now(timezone.utc),
    ))
    test_db.commit()

    from app.workers.tasks import sweep_pending_cover_sheets
    sweep_pending_cover_sheets()

    fake_cs.apply_async.assert_called_once()
    kwargs = fake_cs.apply_async.call_args.kwargs["kwargs"]
    assert kwargs["bundle_type"] == "compliance_evidence_pack"
    assert kwargs["customer_email"] == email

    # Flag cleared so the next sweep is a no-op (no duplicate cover sheets).
    test_db.refresh(user)
    assert user.pending_cover_sheet is False


def test_retry_sweep_requeues_stuck_anchor_until_cap(test_db, mocker):
    """A signed cover sheet whose anchor failed (anchor_failed=True, tx_hash NULL)
    is re-queued by the retry sweep, with a bounded attempt counter so it stops
    after MAX_SWEEP_ATTEMPTS instead of retrying forever.
    """
    from app.core.models import User, Report

    fake_anchor = mocker.patch("app.workers.tasks.anchor_signed_cover_sheet_task")
    fake_anchor.apply_async = mocker.MagicMock()

    user = User(
        email="cep+stuckanchor@booppa.io",
        hashed_password="not-a-real-hash",
        role="VENDOR",
        plan="free",
        company="Anchor Co",
        website="https://example.test",
    )
    test_db.add(user)
    test_db.commit()
    test_db.refresh(user)

    stuck = Report(
        owner_id=user.id,
        framework="compliance_evidence_signed_sheet",
        company_name="Anchor Co",
        status="completed",
        tx_hash=None,
        assessment_data={"anchor_failed": True, "file_hash": "ab" * 32},
    )
    # An exhausted one that must NOT be re-queued.
    capped = Report(
        owner_id=user.id,
        framework="compliance_evidence_signed_sheet",
        company_name="Anchor Co",
        status="completed",
        tx_hash=None,
        assessment_data={"anchor_failed": True, "anchor_sweep_attempts": 8},
    )
    test_db.add_all([stuck, capped])
    test_db.commit()
    stuck_id = str(stuck.id)

    from app.workers.tasks import retry_failed_cover_sheet_anchors
    retry_failed_cover_sheet_anchors()

    # Exactly one re-queue (the stuck one, not the capped one).
    fake_anchor.apply_async.assert_called_once()
    assert fake_anchor.apply_async.call_args.kwargs["kwargs"]["report_id"] == stuck_id

    test_db.expire_all()
    refreshed = test_db.query(Report).filter(Report.id == stuck.id).first()
    assert refreshed.assessment_data["anchor_sweep_attempts"] == 1
